# A makefile for CS31 Lab 1
#
# to build:
#   make
# to clean-up:
#     make clean

CC = gcc

CFLAGS = -g -Wall

TARGETS = lab1

all: $(TARGETS)

lab1: lab1.c
	$(CC) $(CFLAGS) -o lab1 lab1.c

clean:
	$(RM) $(TARGETS)
